# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

lane :increment_version_code do
  version_code = google_play_track_version_codes(
    package_name: "your package name",  #e.g. com.xyz.app
    track: "track-name",                #e.g. alpha
    json_key: "json key file path",
   )
   
   version_code_play_store = version_code[0].to_i
   update_version_code = version_code_play_store + 1
   
   increment_version_code(
    gradle_file_path: "your gradle file path",
    version_code: update_version_code.to_i
   )
end

  desc "Deploy a new version to the Google Play"
  lane :deploy do 
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
      version_code: version_code
    )
  end
end
